name: locket_widget_app
description: "Modern photo and video sharing app with ephemeral content, inspired by Locket Widget. Share moments with friends that disappear after 24 hours."
publish_to: 'none' # Private app - not published to pub.dev

# Version: Major.Minor.Patch+BuildNumber
# Increment for releases: 1.0.0+1 -> 1.0.1+2 -> 1.1.0+3 -> 2.0.0+4
version: 1.0.0+1

environment:
  sdk: ^3.9.2
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  
  # Firebase Backend Services
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_messaging: ^16.0.2
  
  # Media & Camera
  image_picker: ^1.2.0
  camera: ^0.11.0
  video_player: ^2.10.0
  
  # Storage & Persistence
  shared_preferences: ^2.5.3
  path_provider: ^2.1.5
  
  # Networking & Utils
  http: ^1.5.0
  crypto: ^3.0.3
  
  # Permissions & Notifications
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.3
  
  # State Management & Architecture
  provider: ^6.1.2
  
  # Widget Integration
  home_widget: ^0.8.0
  
  # Production Dependencies
  package_info_plus: ^8.0.2       # App version and build info
  device_info_plus: ^10.1.2       # Device information
  connectivity_plus: ^6.0.5       # Network connectivity status
  url_launcher: ^6.3.1            # Launch URLs and external apps
  share_plus: ^10.1.1             # Share content with other apps
  image: ^4.2.0                    # Advanced image processing
  flutter_secure_storage: ^9.2.2  # Secure credential storage
  cached_network_image: ^3.4.1    # Efficient image caching
  flutter_spinkit: ^5.2.1         # Loading animations
  lottie: ^3.1.2                  # Vector animations

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Quality & Linting
  flutter_lints: ^5.0.0
  
  # Testing & Debugging
  integration_test:
    sdk: flutter
  mockito: ^5.4.4                 # Mock objects for testing
  build_runner: ^2.4.12           # Code generation
  
  # Release Tools
  flutter_launcher_icons: ^0.14.1 # Generate app icons
  flutter_native_splash: ^2.4.1   # Generate splash screens

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
# Release and build configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/app_icon.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/app_icon.png"
    background_color: "#8B5CF6"
    theme_color: "#8B5CF6"
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#8B5CF6"
  image: assets/icons/splash_icon.png
  android_12:
    image: assets/icons/splash_icon.png
    icon_background_color: "#8B5CF6"

flutter:
  uses-material-design: true

  # App Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/sounds/
    
  # Custom Fonts (Optional - Uncomment to use custom fonts)
  # fonts:
  #   - family: Poppins
  #     fonts:
  #       - asset: fonts/Poppins-Regular.ttf
  #       - asset: fonts/Poppins-Medium.ttf
  #         weight: 500
  #       - asset: fonts/Poppins-SemiBold.ttf
  #         weight: 600
  #       - asset: fonts/Poppins-Bold.ttf
  #         weight: 700
