// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // This app is Android-only
    if (kIsWeb) {
      throw UnsupportedError(
        'This app is designed for Android only.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
      case TargetPlatform.macOS:
      case TargetPlatform.windows:
      case TargetPlatform.linux:
        throw UnsupportedError(
          'This app is designed for Android only.',
        );
      default:
        throw UnsupportedError(
          'This app is designed for Android only.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3FWNrujtcXka8CeowFYY6KNvoBMg-BUM',
    appId: '1:983305279615:android:6c3ce907cc3d9d792e074a',
    messagingSenderId: '983305279615',
    projectId: 'locket-widget-app-2025',
    storageBucket: 'locket-widget-app-2025.firebasestorage.app',
  );
}
